# Generated by Django 4.0 on 2021-12-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Район',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название улицы')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zone', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улица',
                'ordering': ['name'],
            },
        ),
    ]
